theme: jekyll-theme-minimal
title: Abderrahmane Kasmi
description: AI Student at Dauphine PSL
logo: https://avatars.githubusercontent.com/u/88210982?v=4
show_downloads: false

include:
  - _pages
  
defaults:
  - scope:
      path: "_pages"
      type: pages
